# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# - task: SqlAzureDacpacDeployment@1
#   inputs:
#     azureSubscription: 'internal-azure-subscription'
#     AuthenticationType: 'aadAuthenticationIntegrated'
#     ServerName: 'synapse-network-default-wuvn-sqldwserver'
#     DatabaseName: 'synapse-network-default-wuvn-sqldw'
#     deployType: 'SqlTask'
#     SqlFile: '$(Build.SourcesDirectory)/scripts/load-data.sql'
#     IpDetectionMethod: 'AutoDetect'

- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'sqlQuery'
    SqlFile: '$(Build.SourcesDirectory)/scripts/load-data.sql'
    ServerName: 'synapse-network-default-wuvn-sqldwserver'
    DatabaseName: 'synapse-network-default-wuvn-sqldw'
    AuthScheme: 'sqlServerAuthentication'
    SqlUsername: 'demoadmin'
    SqlPassword: '$(user_password)'