AppRequests
| join (AppTraces) on OperationId
| where Message == "RunResult"
| project TimeGenerated, OperationName, Success, ResultCode, DurationMs, RowsRequested=Properties['RowsRequested'], RowsRetrieved=Properties['RowsRetrieved'], AppRoleName
| where TimeGenerated > ago(30d)
| where AppRoleName contains_cs 'synapse' and OperationName =~ 'GetRows' and DurationMs > 40000
| order by TimeGenerated desc