trigger:
  branches:
    include: 
    - '*'
  paths:
    include: 
    - 'functions/*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  functionsDirectory: '$(Build.SourcesDirectory)/functions'

steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
- pwsh: |
    Write-Host "$(functionsDirectory)"
    dir $(functionsDirectory)
  displayName: 'Test task'

- task: DotNetCoreCLI@2
  displayName: 'Restore function(s) dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    # feedsToUse: 'select'
    # vstsFeed: 'my-vsts-feed' # A series of numbers and letters
    workingDirectory: '$(functionsDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Build function(s) ($(buildConfiguration))'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    workingDirectory: '$(functionsDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Publish function(s) artifacts ($(buildConfiguration))'
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(functionsDirectory)'
    zipAfterPublish: True